###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$terminal = alacritty --working-directory $HOME
$terminalFallback = kitty -d $HOME
$fileManager = nautilus
$menu = rofi -show drun
$appLauncher = rofi -show drun
$lockScreen = hyprlock
$colorPicker = hyprpicker
$browser = firefox
$editor = code
$musicPlayer = spotify
$videoPlayer = mpv