##############################
### WINDOWS AND WORKSPACES ###
##############################


# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrule
# windowrule = float,class:^(kitty)$,title:^(kitty)$

# Ignore maximize requests from apps. You'll probably like this.
windowrule = match:class .*, suppress_event maximize

# Fix some dragging issues with XWayland
windowrule = no_initial_focus on, match:class ^$, match:title ^$, match:xwayland true

# Terminal transparency (keep transparency even when focused)
windowrule = opacity 0.88, match:class ^(Alacritty)$
windowrule = opacity 0.88, match:class ^(kitty)$

# Waybar blur
layerrule = blur true, match:namespace waybar
layerrule = xray true, match:namespace waybar

